### PR TITLE
feat: improve logic to find the next chapter

### LINKED ISSUE #40: Open next - skip the same chapter number
**Is your feature request related to a problem? Please describe.**
To avoid reading the same chapter from different groups. It's a case for a quite a few positions.

**Describe the solution you'd like**
Before opening next file, compare chapter number to previous and skip a file till it's different.

**Describe alternatives you've considered**
As a bonus, stick to the same group (which would solve cases with multi language releases as well).

PS. Great work on this extension! I was positively surprised that someone did so advanced fetcher!

### PR DESCRIPTION
**Pull request by hanatsumi**
This improves the logic used to find the next chapter. The main changes are:
- it will attempt to find a chapter number that is strictly above the current one, avoiding situations like repeating chapters;
- it will prioritize chapters by the same scanlation group.

Closes #40

### CODE REVIEW

**Comment by lenisko** [comment]
@hanatsumi Looks like there's a bug in a new version. On chapter click, nothing happens. There's not even `Downloading chapter...` popup. Would provide a log, but not sure how to get it? Rollbacking a `ChapterListing.lua` fixed it.

**Comment by hanatsumi** [comment]
@lenisko There should be a `crash.log` in the same folder that contains the `plugins` folder, could you share it?

**Comment by lenisko** [comment]
Thanks for pointing it up. Here's a content:

```
10/28/24-00:13:22 INFO  Requesting to  {
  authority = "localhost:30727",
  host = "localhost",
  path = "/settings",
  port = "30727",
  scheme = "http"
} --[[table: 0xb21d68d8]]
10/28/24-00:13:22 WARN  error in wrapped function: plugins/rakuyomi.koplugin/ChapterListing.lua:458: attempt to compare nil with number
stack traceback:
	plugins/rakuyomi.koplugin/ChapterListing.lua:458: in function 'findNextChapter'
	plugins/rakuyomi.koplugin/ChapterListing.lua:235: in function <plugins/rakuyomi.koplugin/ChapterListing.lua:227>
	[C]: in function 'xpcall'
	frontend/ui/trapper.lua:48: in function <frontend/ui/trapper.lua:45>
```

**Comment by hanatsumi** [comment]
Mind sharing which source/manga is it? It should be somewhere inside the `crash.log` file too, if you don't mind sharing it entirely

**Comment by lenisko** [comment]
No problem! Here's complete log, I just wiped it before restarting KOReader.
```
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 10/28/24-00:27:40
 [*] Version: v2024.07

ffi.load: libs/libutf8proc.so.3
ffi.load: blitbuffer
ffi.load: sqlite3
ffi.load: fbink_input
ffi.load (assisted searchpath): ./libs/libfbink_input.so.1
[FBInk] /dev/input/event0: `bd71828-pwrkey` = KEY | POWER_BUTTON
[FBInk] /dev/input/event1: `kx132-accel` = ACCELEROMETER | ROTATION_EVENT
[FBInk] /dev/input/event2: `WacomDigitizer` = TABLET | ROTATION_EVENT
[FBInk] /dev/input/event3: `pt_mt` = TOUCHSCREEN
[FBInk] /dev/input/event4: `stylus-custom` = TABLET | ROTATION_EVENT | SCALED_TABLET
[ko-input] Forked off fake event generator (pid: 7305)
10/28/24-00:27:40 INFO  initializing for device KindleScribe
10/28/24-00:27:40 INFO  framebuffer resolution: {
  h = 2480,
  w = 1860
} --[[table: 0xb6d3c930]]
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
ffi.load: libs/libzstd.so.1
10/28/24-00:27:41 INFO  Loading plugins from directory: plugins
10/28/24-00:27:42 INFO  setting up __gc proxy
10/28/24-00:27:42 INFO  Loading Rakuyomi plugin...
10/28/24-00:27:42 INFO  Spawned HTTP server with PID 7315
10/28/24-00:27:42 INFO  serverCommandWithArgs {
  "plugins/rakuyomi.koplugin/server"
} --[[table: 0xb39f4690]] {
  "plugins/rakuyomi.koplugin/server",
  "./rakuyomi"
} --[[table: 0xb39f4710]]
10/28/24-00:27:42 INFO  Requesting to  {
  authority = "localhost:30727",
  host = "localhost",
  path = "/health-check",
  port = "30727",
  scheme = "http"
} --[[table: 0xb39f4798]]
[2024-10-28T00:27:42Z INFO  server] starting rakuyomi, version: v1.6.0
10/28/24-00:27:43 INFO  Requesting to  {
  authority = "localhost:30727",
  host = "localhost",
  path = "/health-check",
  port = "30727",
  scheme = "http"
} --[[table: 0xb39b7930]]
10/28/24-00:27:55 INFO  Requesting to  {
  authority = "localhost:30727",
  host = "localhost",
  path = "/library",
  port = "30727",
  scheme = "http"
} --[[table: 0xb39f0f18]]
10/28/24-00:28:00 INFO  Requesting to  {
  authority = "localhost:30727",
  host = "localhost",
  path = "/mangas/multi.mangadex/770c61b9-0ef2-460b-8c25-c10ab23349ce/refresh-chapters",
  port = "30727",
  scheme = "http"
} --[[table: 0xb3b962e8]]
10/28/24-00:28:01 INFO  Requesting to  {
  authority = "localhost:30727",
  host = "localhost",
  path = "/mangas/multi.mangadex/770c61b9-0ef2-460b-8c25-c10ab23349ce/chapters",
  port = "30727",
  scheme = "http"
} --[[table: 0xb3cfc350]]
10/28/24-00:28:08 INFO  Requesting to  {
  authority = "localhost:30727",
  host = "localhost",
  path = "/settings",
  port = "30727",
  scheme = "http"
} --[[table: 0xb3b27388]]
10/28/24-00:28:08 WARN  error in wrapped function: plugins/rakuyomi.koplugin/ChapterListing.lua:458: attempt to compare nil with number
stack traceback:
	plugins/rakuyomi.koplugin/ChapterListing.lua:458: in function 'findNextChapter'
	plugins/rakuyomi.koplugin/ChapterListing.lua:235: in function <plugins/rakuyomi.koplugin/ChapterListing.lua:227>
	[C]: in function 'xpcall'
	frontend/ui/trapper.lua:48: in function <frontend/ui/trapper.lua:45>
```

**Comment by hanatsumi** [comment]
@lenisko Should be fixed in v1.6.1

**Pull request merged**
